"""Role constants (stored as plain string on users table)."""
USER = "USER"
SUPER_ADMIN = "SUPER_ADMIN"
EVENT_ADMIN = "EVENT_ADMIN"
ABSTRACT_REVIEWER = "ABSTRACT_REVIEWER"
CONTENT_EDITOR = "CONTENT_EDITOR"
REGISTRATION_MANAGER = "REGISTRATION_MANAGER"
MEDIA_MANAGER = "MEDIA_MANAGER"
ALL_ROLES = (USER, SUPER_ADMIN, EVENT_ADMIN, ABSTRACT_REVIEWER, CONTENT_EDITOR, REGISTRATION_MANAGER, MEDIA_MANAGER)
